"""PageModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import PageModel as OptionalModel
from .strict_models import PageModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        ActionItems,
        Attribution,
        Bobs,
        BottomLeftItem,
        BottomLeftItem1,
        BottomLeftItem2,
        CenterOverlay,
        Collection,
        Colors,
        Content,
        Context,
        DetailScreen,
        Details,
        DynamicCollectionIndex,
        Favorite,
        Grid,
        Grid1,
        Grid2,
        GridItem,
        Image,
        Image2,
        Image3,
        Image5,
        Image6,
        ImageMap,
        ImageMap1,
        ImageUrl,
        Indicators,
        Indicators1,
        Layout,
        Layout1,
        Line1Item,
        Line2Item,
        Meta,
        Meta1,
        Meta2,
        PageModel,
        ParentalRating,
        ProviderBadge,
        ProviderDetails,
        Template,
        TopRightItem,
        TopRightItem1,
        TrackerBeacon,
        TrackerOverrides,
        TrackerOverrides1,
        TrackerOverrides2,
        Treacle,
        ViewItem,
        ViewOption,
    )
else:
    from .optional_models import (
        ActionItems,
        Attribution,
        Bobs,
        BottomLeftItem,
        BottomLeftItem1,
        BottomLeftItem2,
        CenterOverlay,
        Collection,
        Colors,
        Content,
        Context,
        DetailScreen,
        Details,
        DynamicCollectionIndex,
        Favorite,
        Grid,
        Grid1,
        Grid2,
        GridItem,
        Image,
        Image2,
        Image3,
        Image5,
        Image6,
        ImageMap,
        ImageMap1,
        ImageUrl,
        Indicators,
        Indicators1,
        Layout,
        Layout1,
        Line1Item,
        Line2Item,
        Meta,
        Meta1,
        Meta2,
        PageModel,
        ParentalRating,
        ProviderBadge,
        ProviderDetails,
        Template,
        TopRightItem,
        TopRightItem1,
        TrackerBeacon,
        TrackerOverrides,
        TrackerOverrides1,
        TrackerOverrides2,
        Treacle,
        ViewItem,
        ViewOption,
    )

__all__ = [
    "ActionItems",
    "Attribution",
    "Bobs",
    "BottomLeftItem",
    "BottomLeftItem1",
    "BottomLeftItem2",
    "CenterOverlay",
    "Collection",
    "Colors",
    "Content",
    "Context",
    "DetailScreen",
    "Details",
    "DynamicCollectionIndex",
    "Favorite",
    "Grid",
    "Grid1",
    "Grid2",
    "GridItem",
    "Image",
    "Image2",
    "Image3",
    "Image5",
    "Image6",
    "ImageMap",
    "ImageMap1",
    "ImageUrl",
    "Indicators",
    "Indicators1",
    "Layout",
    "Layout1",
    "Line1Item",
    "Line2Item",
    "Meta",
    "Meta1",
    "Meta2",
    "PageModel",
    "ParentalRating",
    "ProviderBadge",
    "ProviderDetails",
    "Template",
    "TopRightItem",
    "TopRightItem1",
    "TrackerBeacon",
    "TrackerOverrides",
    "TrackerOverrides1",
    "TrackerOverrides2",
    "Treacle",
    "ViewItem",
    "ViewOption",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> PageModel:
    """Read a downloaded file into PageModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
