# TODO: Validate
"""Query parameters the detail screen asks for."""

SEPARATOR = ","
"""What the API separates the values of a list parameter with."""

EXPAND = SEPARATOR.join(
    (
        "next",
        "credits",
        "next.series",
        "viewOptions",
        "categoryObjects",
        "viewOptions.providerDetails",
        "series",
        "season",
        "episodes",
        "season.episodes",
        "season.episodes.viewOptions.providerDetails",
        "seasons.episodes.viewOptions.providerDetails",
        "seasons",
        "seasons[0]",
        "seasons[0].episodes",
    ),
)
"""Relations to inline into the response instead of returning a reference."""

INCLUDE = SEPARATOR.join(
    (
        "type",
        "title",
        "imageMap.detailPoster",
        "imageMap.detailBackground",
        "bobs.detailScreen",
        "categoryObjects",
        "runTimeSeconds",
        "castAndCrew",
        "savable",
        "stationDma",
        "kidsDirected",
        "releaseDate",
        "releaseYear",
        "description",
        "descriptions",
        "indicators",
        "genres",
        "credits.birthDate",
        "credits.meta",
        "credits.order",
        "credits.name",
        "credits.role",
        "credits.personId",
        "credits.imageMap.detailPoster",
        "parentalRatings",
        "reverseChronological",
        "contentRatingClass",
        "languageDialogBody",
        "detailScreenOptions",
        "viewOptions",
        "episodeNumber",
        "seasonNumber",
        "sportInfo",
        "eventState",
        "next.series.title",
        "series.title",
        "season",
        "season.episodes.title",
        "season.episodes.description",
        "season.episodes.descriptions.40",
        "season.episodes.descriptions.60",
        "season.episodes.episodeNumber",
        "season.episodes.seasonNumber",
        "season.episodes.images",
        "season.episodes.imageMap.grid",
        "season.episodes.indicators",
        "season.episodes.releaseDate",
        "season.episodes.viewOptions.isUnlocked",
        "season.episodes.viewOptions.media.duration",
        "season.episodes.viewOptions.providerId",
        "season.episodes.viewOptions.providerProductId",
        "season.episodes.viewOptions.providerDetails.providerProductIds",
        "seasons.title",
        "seasons.seasonNumber",
        "seasons.description",
        "seasons.descriptions",
        "seasons.releaseYear",
        "seasons.castAndCrew",
        "seasons.credits.birthDate",
        "seasons.credits.meta",
        "seasons.credits.order",
        "seasons.credits.name",
        "seasons.credits.role",
        "seasons.credits.personId",
        "seasons.credits.images",
        "seasons.imageMap.detailBackground",
        "seasons.episodes.title",
        "seasons.episodes.description",
        "seasons.episodes.descriptions.40",
        "seasons.episodes.descriptions.60",
        "seasons.episodes.episodeNumber",
        "seasons.episodes.seasonNumber",
        "seasons.episodes.images",
        "seasons.episodes.imageMap.grid",
        "seasons.episodes.indicators",
        "seasons.episodes.releaseDate",
        "seasons.episodes.viewOptions",
        "seasons.episodes.viewOptions.isUnlocked",
        "seasons.episodes.viewOptions.media.duration",
        "seasons.episodes.viewOptions.providerId",
        "seasons.episodes.viewOptions.providerProductId",
        "seasons.episodes.viewOptions.providerDetails.providerProductIds",
        "episodes.episodeNumber",
        "episodes.seasonNumber",
        "episodes.viewOptions",
        "viewOptions.disabled",
        "viewOptions.providerId",
        "viewOptions.providerProductId",
        "viewOptions.discreteLiveEvent",
        "viewOptions.license",
        "viewOptions.media",
        "viewOptions.channelId",
        "viewOptions.adsContentId",
        "viewOptions.adsProviderId",
        "viewOptions.playId",
        "viewOptions.isUnlocked",
        "viewOptions.providerName",
        "viewOptions.bobs.detailScreen",
        "viewOptions.mvpdLivefeedId",
    ),
)
"""Fields to return. Without it the response carries every known field and is
several times larger."""

FILTER = SEPARATOR.join(
    (
        "categoryObjects:genreAppropriate%20eq%20true",
        "seasons.episodes:(not%20empty(viewOptions)):all",
    ),
)
"""Drops categories flagged as inappropriate and episodes that cannot be played.

The spaces are pre-encoded because the API expects them escaped inside the
already escaped value."""

FEATURE_INCLUDE = SEPARATOR.join(("bookmark", "watchlist", "linearSchedule"))
"""Per-account features to annotate the response with."""
